### ISSUE TITLE
Flush privacy service cache

### ISSUE THREAD

**Issue by psyoptix** [M66B/XPrivacy#1678]
Such a functionality would permit a much more fine grained access control model since a user could then enable capabilities for an app(s) not just in terms of absolute Yes or No but also conditioned on a huge variety of run-time conditions being met. For example this could allow revoking permissions needed by an app unless a run-time condition is met explicitly indicating that the user now intends to make use of those capabilities.

Example use cases:
- Create a toggle to enter and leave "Navigation Mode" entailing turning on/off GPS, fine grained location service, and switching location relevant privacy restrictions on relevant navigation apps in one clean action. The first two are possible with Tasker alone but the third part would require the requested extension of XPrivacy.
- Enable location access for google play service (and maps) only when Maps is open.
- Automatically enable location access only when connected to home wifi to benefit from location specific search but avoid having movements tracked.
- Enable NFC capabilities only when myNFCapp running in foreground.
- Turn sending SMS and outgoing Phone Calls permissions off globally while screen off (or even unless dialler or SMSapp running in foreground).

**Comment by Cerberus-tm** [comment]
@an0n981 Hi! Did you ever finish your Xprivacy Tasker plug-in, or what did you make in the end? I'm trying to do a similar thing with Tasker and shell commands to the Xprivacy database, but I'd love to know more about what you did.

(I'm trying to make Tasker modify the Xprivacy database when a certain app is in the foreground, like Google Maps, then modify again when it is no longer in the foreground. I think I have all the building blocks working, but for far the problem I'm running into is that Tasker's detection of which app is in the foreground seems to be unreliable...or it may be Android that is unreliable in registering which app is in the foreground...

I could use work-arounds, like Tasker shortcuts or timers or repeated checking rather than Tasker's standard app contexts, but those all have disadvantages.)

**Comment by Cerberus-tm** [comment]
Okay, I have found the cause of the unreliable triggers: Tasker by default only checks for foreground applications ever 1.5 seconds. You can set it to a lower value in Tasker's preferences, which may cause slightly higher battery usage. I tried that, and it really helped.

Another, probably even more reliable trigger I found in Tasker is "UI – New Window". This can trigger a task whenever a new window is opened, so it triggers whenever you switch to an application. It seemed to be completely reliable, so far. The disadvantage is that the task is triggered every time you switch to a different window, not only when you switch to certain apps, as with the "Application" trigger. As to battery usage and general phone performance, I haven't noticed any significant effect yet with "UI – New Window" on all the time; but that is difficult to measure, and I have a reasonably fast phone (LG G2).
