### ISSUE TITLE
[Request] Resend/or delay biz.bokhorst.xprivacy.action.ACTIVE

### ISSUE THREAD

**Issue by an0n981** [M66B/XPrivacy#2113]
After an update to Tasker it no longer starts up in time to receive the intent at boot (XPrivacy is just way to fast ;). Therefore a request to either delay the broadcast or send it a second time.

**Comment by M66B** [comment]
Delaying is not a good idea IMHO and sending the intent another time raises the question when.
Isn't it a better solution to have a fail-safe in Tasker?

**Comment by an0n981** [comment]
The issue is the following:
When the phone shuts down it triggers airplane mode and a few other items.
After the reboot Tasker waits for the intent from XPrivacy and only then enables radios etc.
The issue is that after a Tasker update, it has somehow moved down in the boot order to the point that the intent is sent from XPrivacy before is able to accept it.

**Comment by M66B** [comment]
I don't see a good solution here, so I am closing this issue for now.

**Comment by an0n981** [comment]
:(

**Comment by Cerberus-tm** [comment]
As a work-around, you could create a Tasker profile with the condition "Event → On boot". Then you could have Xprivacy provide a fake value to Tasker, so that Tasker may check whether Xprivacy is active based on that value. If you set ICC ID to "999" for Tasker in Xprivacy and restrict "Phone → GetSIMSerialNumber", then Tasker will get "999" if it checks for the variable %SIMNUM. So you could add "Variable %SIMNUM = 999" as a second condition for the Tasker profile above. Only if both conditions are matched (boot & variable=999) shall Tasker enable the radios.

**Comment by an0n981** [comment]
you're a genius ;)

**Comment by Cerberus-tm** [comment]
Heh thanks, but it's still kind of not the way things were intended to work. Oh, well, I guess Xprivacy and Tasker are not the way Google wants Android to work anyway!

**Comment by an0n981** [comment]
Just for the record, using this will cause the alarm to trigger if there is no service available.

**Comment by Cerberus-tm** [comment]
Hmm what alarm, and what service? The Xprivacy service?

**Comment by an0n981** [comment]
what I meant by service was telephone network connectivity. If the phone is currently out of service range the value %SIMNUM can't be read which would trigger the 'Alarm', the reason why we are checking for the value in the first place. An alternative is to check for %DEVTID and set a custom IMEI in XPrivacy for Tasker. This value is available even is there is no SIM card installed in the device.

**Comment by Cerberus-tm** [comment]
Ah, I didn't know that. I just picked a random value to be honest, but %DEVTID sounds better, then.
