### ISSUE TITLE
Submit just 10 applications at a time?

### ISSUE THREAD

**Issue by mr-gosh** [M66B/XPrivacy#2126]
I donated to xprivacy and wanted to begin to give my profiles to the crowd sourced site.
But you make it really difficult to let the people contribute...

I had to select by hand 10 apps and upload the working profiles to your server...

I was searching for a "upload all" and a "sync weekly" function for contributing profiles....

**Comment by M66B** [comment]
First of all thanks for your intention to help others.

This has been discussed on the XDA XPrivacy forum before, but I understand you were not able to read all messages of the forum, because it is so large.

This limitation exists to prevent people from submitting rubbish, like unset or unfinished restrictions.

**Comment by mr-gosh** [comment]
I still think, there should be a way to submit working configs more easily.
I realised that most uploaded profiles doesn't supress access to static device ids - and thats nearly the most important area - so i still have to create all my profiles myself - because the uploaded config are too unrestricted...

i'll think about it...
