### ISSUE TITLE
[Issue] Restrict On-Demand not working

### ISSUE THREAD

**Issue by poeypresents** [M66B/XPrivacy#2139]
I can't get restrict on-demand to work after loading new rom and importing settings....I have tried resetting Xprivacy Settings, App Settings, Reinstalling Xposed...still cannot get the pop-up overlay for the restrictions to show...

thanks for your help

**Comment by M66B** [comment]
Please provide a logcat with XPrivacy debug log enabled. You can also try the quirk 'freeze'.

**Comment by poeypresents** [comment]
https://www.dropbox.com/s/74n8r6ke9u7afny/logcat_and_device_info.zip?dl=0

**Comment by jimbo1qaz** [comment]
I experienced the same bug and found the root cause.
XPrivacy has a background autostart service which must be started for prompts to show up.
When I had Xposed Boot Manager installed, and XPrivacy on-boot turned off:
The XPrivacy service is not started when you open the XPrivacy settings manager.
The XPrivacy service is not started when an app performs a promptable operation, instead using the default action instead.

Whether these are XPrivacy behaviors or consequences of Boot Manager, I don't know for sure. It may be a good idea to warn for nonfunctional service, or autostart (if the latter, people won't know why the bug's there, which is bad).

**Comment by licaon-kter** [comment]
@jimbo1qaz Thank you for the explanation, I've been restarting the device 2 dozen times to no avail, although some reboots were with XPrivacy enabled in Xposed Bootmanager too. Now it works.

@M66B Do start whatever background service you need on boot but also on app start, this was an exercise in frustration, no visible errors, nothing, and I recall having this issue on every system reinstall, ondemand starts working after some reboots, out of the blue.

**Comment by M66B** [comment]
@licaon-kter XPrivacy has no background service and XPrivacy needs to be started before Android runs, else it wont work.

**Comment by jimbo1qaz** [comment]
If so, can you pop up an alert, "xprivacy has not been started, check
BootManager", or something like that?

**Comment by M66B** [comment]
There is already a notification about that.

**Comment by jimbo1qaz** [comment]
okay.

**Comment by licaon-kter** [comment]
@M66B Thanks
