### ISSUE TITLE
Google Advertisement ID is not restricted

### ISSUE THREAD

**Issue by vikaskumar615** [M66B/XPrivacy#2166]
xprivacy is not restricting Google Advertisement ID.It allows picking of original Advertisement ID.

**Comment by M66B** [comment]
Which Android version?
How did you test this?
I am quite sure it works on Android versions before Lollipop.

**Comment by vikaskumar615** [comment]
on Kitkat.  I have tested it on many apps.

**Comment by vikaskumar615** [comment]
IMEI, Android ID all are working well but there is something wrong with advertisement id

**Comment by M66B** [comment]
Are you sure you are not seeing a fake value?

The restriction is straightforward and has been tested to be working:
https://github.com/M66B/XPrivacy/blob/master/src/biz/bokhorst/xprivacy/XAdvertisingIdClientInfo.java

There is just one way to get the advertising Id:
https://developer.android.com/reference/com/google/android/gms/ads/identifier/AdvertisingIdClient.Info.html

Note that I cannot check things, since Xposed doesn't work on my device.

**Comment by TameOfGroans** [comment]
Since XPosed does not work on your device would you be averse to starting a crowd fund project to buy you a preferred device for such testing?

**Comment by M66B** [comment]
I have only one device, a Nexus 5 (I gave all my old devices away), which should suffice for XPrivacy development. The main problem is Xposed itself. Xposed is not yet available for Android 5.1 and quite unstable, at least in combination with XPrivacy. The reason for the instability is a know Xposed bug. The developer of Xposed has said that both Android 5.1 support and the bug do not have priority.

A second device for Xposed development would be handy, since I use the same device both for private and business purposes, but that doesn't take away the Xposed problems.

**Comment by M66B** [comment]
This XDA comment has more information about the current project status:
http://forum.xda-developers.com/showpost.php?p=59352424&postcount=14092
