### ISSUE TITLE
Create "virtual" contact provider for restricted App

### ISSUE THREAD

**Issue by Eun** [M66B/XPrivacy#2179]
Hi there.
First of all great app :+1: 

I wonder if its possible to create a kind of virtual contact provider for an restricted App?

Lets make an example:

You dont want that an app has access to your contacts.
It should use its own "container" where It is allowed to read and write contacts

One way could be to restrict an app to a specific provider.

There is an app out there that has the ability to give you a local provider.
www.fjsoft.at/mylocalaccount.apk 
It would be nice if it is possible to restrict the app to this provider only.

**Comment by wbedard** [comment]
For the benefit of others, could you please describe a specific "use-case" (i.e. specific app and functionality...) where the current version of XPrivacy does not meet your needs.  You clearly described what you want but, given the significant amount of time/effort required to add this capability, it would help to understand how much value the XPrivacy user community would gain from it.  If nothing else, it might help the more creative XPrivacy users help you find a successful "workaround" in case your desired functionality cannot be added.  Thanks in advance!

**Comment by Eun** [comment]
Ok,
lets take WhatsApp as an example:

WhatsApp *probably* syncs other data than the number, I want to suppress this.
So I want to create a new provider using `MyLocalAccount` and force WhatsApp to only use the `MyLocalAccount` provider.
In the `MyLocalAccount` provider I will add the Users specifying the name and number only.

**Comment by wbedard** [comment]
Aha, I see...thanks for the very clear explanation!  Until Marcel chimes in with his thoughts, I would not hesitate to post a summary of this issue (linking back here for specifics) in the XDA forum thread.  There are a few very clever users who might suggest some missing elements that could help you accomplish your goal without requiring add'l development.

**Comment by Cerberus-tm** [comment]
You could do the following as a work-around, which will I think not require a lot more work than if this feature were implemented in Xprivacy. You probably need one of the paid versions of Xprivacy (I always forget which one).

You copy all the contacts that you want Whatsapp to access. You could prefix them with "A_" to have them appear all together at the top of your contact picker in Xprivacy.

From those contacts, you remove all information except the phone numbers.

In Xprivacy, you restrict "Contacts" for Whatsapp, but you pick allowed contacts (Menu → Select Contacts to allow). You pick only the "A_" ones. Done!

Note that Whatsapp stores lots of information on its servers, so it is possible that they already have your contacts on their servers, and they may be restored automatically if you do this, so it will be hard to check whether it works properly. In other words, if a contact is still visible to Whatsapp even though it's supposed to be restricted, that may be because it came from the server.

**Comment by M66B** [comment]
I don't see why the existing contact restrictions cannot be used for what you want.

**Comment by M66B** [comment]
[Same question on XDA](http://forum.xda-developers.com/xposed/modules/xprivacy-ultimate-android-privacy-app-t2320783/page1453#post60264617), so I am closing this issue.

**Comment by Eun** [comment]
@Cerberus-tm 
Yes that is a way, this has one disadvantage:
If a new contact writes an message you have the possibility to add the new contact directly.
After you added the contact you still need to enable the access to this account.

@M66B this is me as @wbedard  suggested I created a issue there as well.
The difference in this feature would be the tree hierarchy:

+ Contacts
+---------+ Google Account Provider
|            +-------- Account A
|            +-------- Account B
+---------+ Local Account Provider
             +-------- Account A
             +-------- Account B

If you deny access to Google Account Provider, the app wont see any contacts that are managed by the Google Account Provider.

**Comment by M66B** [comment]
You are welcome to contribute code, if you are willing to maintain it as well, but this can be done by restricting contacts and allowing individual contacts as well.

**Comment by Eun** [comment]
So you say that it is already possible to allow a whole *group* of contacts? Even if the group gets a new member by time?

**Comment by Eun** [comment]
I saw that you are using groups as well, so probably using the groups would achieve the same result.

**Comment by M66B** [comment]
A few more remarks:

* There is no Google contact provider, but only a Android contact provider
* Building a replacement for the Android contact provider is a *huge* project
* Even if this succeeded, uninstalling XPrivacy would make the contact go away, in effect making application dependent of XPrivacy. This is undesirable

**Comment by Cerberus-tm** [comment]
@Eun  That is true, Xprivacy has no group management for contacts. Perhaps someone could build a group feature for Xprivacy, but then somehow Xprivacy would have to be notified when a new contact presents himself through Whatsapp...it sounds like a huge project.

One possibility, though, would perhaps be to have an option in Xprivacy to "automatically allow new contacts" for an application. That way, you would have to change things by hand in Xprivacy if you wanted to add, say, an address to a contact that you wanted to block for Whatsapp, but any new (automatic) contacts through Whatsapp would be allowed automatically. Not sure whether this would be feasible, though.

**Comment by M66B** [comment]
XPrivacy should not have group management for contacts, since it is not a contact manager. XPrivacy is as it is already complex enough.

Automatically allow new contacts is privacy wise not a solution. The user should allow things, since he/she is the only one who can judge if it is allowed to allow ;-)

**Comment by Cerberus-tm** [comment]
I understand. And a pop up from Xprivacy "allow this contact for the following applications: [list of apps with tick marks]" whenever a new contact is created sounds complicated to implement, right?
