### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by xtsss** [M66B/XPrivacy#2210]
Unfortunately,  on samsung s5 g900F klte international,
on this rom:
http://forum.xda-developers.com/showthread.php?t=2716535
(lollipop TW)
with xposed installed as in this topic:
http://forum.xda-developers.com/xposed/unofficial-xposed-samsung-lollipop-t3113463
xprivacy works - but lags phone, everything is slower. I tried to turn off every function, data usage etc... but it made small change - still slow, so despite my pro key bought by paypal i am not using it now, waiting for speed up.

**Comment by M66B** [comment]
Xposed/XPrivacy have very little overhead and will not noticeable slow down things.

What could slow down things is a slow data storage partition. See the FAQ #1 for a potential solution.

Note that there is nothing I can do to fix this by changing XPrivacy, because it will not speed up your device or fix hardware problems (which some Samsung devices, notably the S4 and S5, are know to have).
