### ISSUE TITLE
On-demand dialogue clears permanent restrictions when "deny" is pressed

### ISSUE THREAD

**Issue by 7astro** [M66B/XPrivacy#2227]
Ok, I hope this one is legit. 
**Initial situation:**
* Choose any app that uses dangerous functions
* Manually apply permanent restrictions for dangerous functions (e.g. every function in category "Shell")
* Manually apply on-demand restrictions to a subset of the above restrictions

**Where it goes wrong:**
1. Open app and wait until the respective on-demand dialogue will pop-up
2. Make sure "expert mode" is unckecked, deny permission
3. Restrictions get overwritten:
   * on-demand dialogue won't pop-up for this category any more -  thus on-demand restrictions will be cleared for this category ( which is perfectly ok behaviour)
   * the currently denied function will have a permanent restriction applied to it ( ok as well )
   * but the app will have access to all other function you previously restricted - their permanent restrictions will be cleared

**Comment by M66B** [comment]
In any case you have clearly described the problem you have, which is unfortunately not always the case. I have however one question: "manually apply" does this mean allow or deny?

On demand restricting can be enabled/disable both on category and function level. If you answer an on demand dialog with allow/deny for the category it will be disable for the whole category and the whole category will be allowed/denied/

**Comment by 7astro** [comment]
by "manually" I mean putting a check/question mark for every single function. I do understand how restriction work on category basis, that's why I said it is to be an ok behaviour. I tested it on Elixir for Shell while accessing logcat

**Comment by 7astro** [comment]
the main point is here dangerous/red functions which are not "internally white-listed" for on-demand restrictions. And by those I mean the red ones that get question mark applied, when one applies an on-demand restriction for a whole category

**Comment by M66B** [comment]
"*Make sure "expert mode" is unckecked, deny permission*": the category will be denied.
"*but the app will have access to all other function you previously restricted - their permanent restrictions will be cleared*": are you sure about this and how did you determine this.

As you can see here:

https://github.com/M66B/XPrivacy/blob/master/src/biz/bokhorst/xprivacy/PrivacyService.java#L2151 
https://github.com/M66B/XPrivacy/blob/master/src/biz/bokhorst/xprivacy/PrivacyService.java#L361

category restrictions are being set when you selected this. There is no other flow (condition) applicable. This means there is going something terribly wrong or that you are doing/seeing something wrong.

**Comment by M66B** [comment]
Okay, now is clear what your problem is.

This is however by design. Setting category restrictions never set dangerous restrictions. This is because this has proven to result in a lot of problems for novice users.

There are two use cases

1. You are novice user: use the category restrictions
2. You are expert user: use the function restrictions

Expert users can change dangerous restrictions into normal restrictions (long press in the template view).

**Comment by 7astro** [comment]
Thats right, but I know it. Please look through this example: 
* Use default templates ( not changes made )
* Apply default template to Elixir
* Restrict all function in Elixir in category Shell (permanently and on-demand)
* Open Elixir (deny Identification category/ allow view category) and go to logs
* On-demand dialogue for Shell(sh) will pop-up, use non-expert mode and deny, no logs will be shown
* Go to Xprivacy and see that only sh has a permanent restriction intact, others are ALLOWED

**Comment by 7astro** [comment]
So I think in the above post, you are implying that the one who restrict dangerous functions should never use non-expert mode anyway? This point is not well communicated in the FAQ imo. Another problem is the way the subset of dangerous functions is managed - namely globally and for all templates.

**Comment by M66B** [comment]
"*Go to Xprivacy and see that only sh has a permanent restriction intact, others are ALLOWED*": they were allowed and to be asked in the first place, so there wasn't anything changed.

If the default would be deny when on demand restricting is enabled, a lot of (novice) users would have troubles (and actually did have a lot of troubles when this was in some beta releases) when the on demand restricting dialog times out and default denies (resulting in crashing application and sometimes even in data lost).

"*So I think in the above post, you are implying that the ones who restrict dangerous functions should never use non-expert mode anyway?*": yes. Basically dangerous restrictions have to be set manually by default for this very same reason.

"*Another problem is the way the subset of dangerous functions is managed - namely globally and for all templates.*": if a restriction is dangerous or not has to be defined somewhere and doing this per application would be more complicated (and not understood by a lot of user) and be at the cost of performance (since this would result in evaluating this real-time per application).

**Comment by M66B** [comment]
To be practical: set your template to deny and ask always, make all restrictions non dangerous and you will have what you want. This is what most expert users do (maybe with the exception of some functions, but this will come with experience).

**Comment by 7astro** [comment]
*"they were allowed and to be asked in the first place, so there wasn't anything changed."* 
I don't quite get the point. The only "mistake", as I see it, was for me to implicitly check the "apply to entire category" option, which triggered the novice protection mechanism and cleared the dangerous restrictions. 

This brings me to another point -  in the expert mode it would be helpful if the "apply to entire category" would be unchecked as default. Actually I doubt it does there much help:
* Individual non-dangerous functions, which you want to be allowed/denied, get overwritten on category deny/allow
* Dangerous functions are likely to be allowed despite of your category deny decision
* I suppose category timer will only work on the non-dangerous subset, subset you cannot adjust individually
* In the case you proposed (with no dangerous functions) I would unlikely want to deny every function in the category by pressing category deny 

By the way, I value this novice protection mechanism, it is a necessary thing. The reason, why I will unlikely disable dangerous functions, is the on-demand red window that indicates to me that the particular restriction is generally known to cause problems.

**Comment by M66B** [comment]
The category check box state is remembered, so you can set it as you like.

Changing the behavior of the on demand restricting dialog is not really an option anymore, considering the many existing users.
