### ISSUE TITLE
There are a lot of things to be restricted

### ISSUE THREAD

**Issue by KOLANICH** [M66B/XPrivacy#2247]
1 install https://play.google.com/store/apps/details?id=com.finalwire.aida64
2 restrict everything (including restrictions marked with red color)
3 run
4 enjoy leaked identifiers

**Comment by M66B** [comment]
If you want something fixed, you need to describe steps to reproduce and details about what is wrong. Just saying it doesn't work, is insufficient.

**Comment by M66B** [comment]
Please read this carefully:
https://github.com/M66B/XPrivacy#support

**Comment by KOLANICH** [comment]
When everything is restricted, the following info is stil leaking:
1 device model
2 info about platform (both software and hardware)
3 info about performance profiles including governor name
4 info about current language (allows to determine nationality of owner)
5 info about screen and gpu
6 battery capacity
All of theese allows to fingerprint OS carefully to choose the exploits correctly.

7 access to momental states of cores allows to distinguish between types of activity on the device (at least wheither user is doing something like typing text in primitive editor or using resource-eating app like game, but It can be probably possible using machine learning derive the app the user is using in the moment).

8 wlan signal strength (allows tracking via sending uniq id of the app installation and signal strength to external server and identifiying the router by ip address and fingerprint of software running on it)

When I allow Camera.Permission, it gets info about camera modules, which also allows to distinguish between devices. I think that the app not allowed to use features of the sensor should know nothing about them.

**Comment by M66B** [comment]
Most of this information will not be restricted. There is a FAQ about this. Fingerprinting is something which cannot be prevented anyway under Android, since Android exposes really a lot of stuff (this is just a tiny part of it).

Let me know if you find real unique identifiers though, which can identify you.

**Comment by an0n981** [comment]
Tracking based purely on power supply monitoring:
http://www.bbc.com/news/technology-31587621

**Comment by KOLANICH** [comment]
@an0n981, see #2176

**Comment by M66B** [comment]
A little more explanation: fighting fingerprinting is a lost battle, because Android and the underlying Linux kernel are just too open. Restricting the Linux kernel cannot really be done by an Xposed module (only indirectly by restricting the file system, but this can be circumvented by native code). There is also another problem: too many restrictions will slow down the system too much. It doesn't matter if a restriction is active or not, since checking if a restriction needs to be applied takes most of the time in most cases. There is also the problem that certain restrictions can lead to problems with developers with deep pockets, like game developers. This is one of the reasons I don't want the device model be changed by a restriction for example. Last but not least, too many restrictions will not be maintainable. There are already too many, more than 400. There is still just one developer, who has other things to do and other interested as well.

**Comment by Cerberus-tm** [comment]
Hi Marcel, thank you for that explanation, very enlightening. It is incredible and amazing how you have made the world's best privacy application on your own! There was one thing I didn't understand: 

[quote]There is also the problem that certain restrictions can lead to problems with developers with deep pockets, like game developers."[/quote]

What is that about?

**Comment by M66B** [comment]
It simply means that I don't want unnecessary trouble, in the interest of everybody, with other developers. Restrictions can be used for game cheating for example.

**Comment by KOLANICH** [comment]
>this can be circumvented by native code
Is it possible to use LXC to fix it?

**Comment by M66B** [comment]
Maybe, but this is far outside the scope of XPrivacy.

**Comment by Cerberus-tm** [comment]
Okay, so it is about cheating. How could one cheat by faking one's device?

**Comment by M66B** [comment]
Cheating and faking the device model are just examples.
