### ISSUE TITLE
[Bug] Problem(s) with whitelisting contacts

### ISSUE THREAD

**Issue by Gitoffthelawn** [M66B/XPrivacy#2256]
When whitelisting contacts, when I select *Phone/Coworkers* from the menu, and then select some contacts, those contact selections are not reflected when clicking on the 'W' with a a circle around it.

Note that this example uses *offline* contacts (hence the *Phone* in *Phone/Coworkers*).

It might be the same bug, or a different one, but selecting contacts from *Phone/Coworkers* results in the ability to select each individual contact number (when a contact has more than one phone number).  Selecting contacts by clicking on the 'W' with a circle around it does not allow that granularity, and automatically includes all contact numbers for each contact selected.

**Comment by M66B** [comment]
This has been discussed in the XDA XPrivacy forum not so long ago, so please check the discussion about this and what I said about it. The discussion was about WhatsApp, but it is the same question.

**Comment by Gitoffthelawn** [comment]
Are you referencing posts 15,508-15,510?

If so, I think that is something different.  That involves another app (WhatsApp) interacting and copying contacts.  What I experienced happens directly within XPrivacy.

Or am I referencing the incorrect posts?

**Comment by M66B** [comment]
There are no bugs in contact white/black listing, but it may not function as you expect/want to. This cannot be fixed without putting a lot of time into this. I have put already really a lot of time in contact white/black listing and I am not willing to put more time into it, also because I expect it can only be improved marginally. The Android contact provider is complex and not designed with XPrivacy in mind.
