### ISSUE TITLE
Minor: Keyboard does not pop up when selecting XPrivacy search field

### ISSUE THREAD

**Issue by Gitoffthelawn** [M66B/XPrivacy#2288]
When selecting the XPrivacy search field, the keyboard does not pop up.  Selecting the field again reliably results in the keyboard popping up.

Test System:
1. Test Device XPrivacy Version: PRO 3.6.19 (481). Running in compatibility mode.
2. Test Device Xposed Version: 2.6.1
3. Test Device OS Version: Android 4.4.2 (LGE).

If this is something you want to pursue fixing, I can provide more information.

**Comment by M66B** [comment]
This is how it is supposed to work (according to Google).
The search field is implemented by using the compatibility library of Google.

**Comment by M66B** [comment]
Before you ask: this cannot be changed, I have looked into it in the past.

**Comment by Gitoffthelawn** [comment]
*This is how it is supposed to work (according to Google).*

That's odd.  I would love to read the Google reference if you have it handy,

**Comment by M66B** [comment]
https://developer.android.com/reference/android/support/v7/widget/SearchView.html

**Comment by Gitoffthelawn** [comment]
Thanks for the reference. I'll read it.

**Comment by francwalter** [comment]
@Gitoffthelawn Did you read it? 
I noticed this little issue also since long.
I thought that the automatic popup were the default. At least in many other apps it is.
But in that reference I don't see it mentioned or I don't understand it.
In another app, Aard2, here in github as well, I posted a similar issue and it was fixed.
But maybe not the same type of search field. Don't know much.

**Comment by francwalter** [comment]
https://github.com/itkach/aard2-android/issues/48
This was that
