### ISSUE TITLE
Block apps writing files on our phones.

### ISSUE THREAD

**Issue by SWADED** [M66B/XPrivacy#2305]
Not only block apps from reading files but It would be very helpful if we could block apps writing files on our phones.
For instance I can block a app from reading a analytics file/database, I would like to prevent this app from making this file/database in the first place.

**Comment by M66B** [comment]
XPrivacy is meant to prevent reading privacy sensitive information only.

**Comment by nita27** [comment]
I don't know what this is but can you please unblock my application I
didn't do any of this thank you

**Comment by M66B** [comment]
Any restriction is done by yourself, so unrestrict what you restricted.
Please use the XDA XPrivacy forum for question.
GitHub is for feature requests and bugs only.

**Comment by Cerberus-tm** [comment]
Can apps also overwrite files, even when they can't read them? Doesn't result in many unforeseen potential data leakages? If they can e.g. overwrite the URL whitelist of Xprivacy or of some other app...

I can't really think of a scenario where an app should be allowed to write to a file but not read it. Wouldn't it make more sense to always conjoin the two abilities? That is actually how I thought it worked...

**Comment by M66B** [comment]
Only reading files can expose privacy sensitive data, not writing files. Making it possible to block writing files will only result in questions, without any benefit to your privacy.

**Comment by Cerberus-tm** [comment]
Reading files is the most obvious and common way to expose sensitive data. But suppose you had a firewall app installed that was using a whitelist, and I, the evil app, overwrite your whitelist with something of my choosing. Then I can cause any app I choose to bypass the firewall unnoticed. So e.g. apps that contain ads with tracking cookies/pixels/scripts could use this method to delete the whitelists from common firewall applications and leak all sorts of data.

In other words, allowing apps to write to files when this *isn't necessary*, and when it *isn't expected by users* that they are allowed to do so, creates a whole extra, unnecessary attack vector that can be used to sabotage other apps in order to leak data. I'm sure there are other, unknown ways in which you could use the overwriting of files to cause data leaks, ways I haven't thought of yet...

Admittedly, this will be much less common than leaks resulting from the *reading* of files, but still. As to confusion, you could make it an expert function, or give users a pop-up when they restrict the permission. Of course, if you think it's too complicated, I understand you might not want to implement this.

**Comment by M66B** [comment]
Applications cannot read and write files of other applications without root permissions.

**Comment by Cerberus-tm** [comment]
Oh! That is good, I guess, and it makes sense. My apologies.
Hmm I tried to Google which files normal apps *can* read/write, but I couldn't find it. I presume normal apps can't see any files in system folders. But an app can presumably see some other files outside the app's own folder?

**Comment by M66B** [comment]
An application cannot see files in system folders, but can see files in shared storage if it has appropriate permissions.
