### ISSUE TITLE
Privacy service not found.

### ISSUE THREAD

**Issue by codecrak** [M66B/XPrivacy#2352]
Did everything..looked for another guards..cleaned the phone, yet nothing seems to work.

ZTE Nubia Z9 mini .lollipop 5.1.1

**Comment by M66B** [comment]
Please provide a logcat

**Comment by codecrak** [comment]
[2016-05-22-17-42-31.txt](https://github.com/M66B/XPrivacy/files/276302/2016-05-22-17-42-31.txt)

**Comment by codecrak** [comment]
Here it is sir

**Comment by M66B** [comment]
The logcat needs to be captured from your PC starting before you turn your device on.

**Comment by codecrak** [comment]
Via adb ?

**Comment by M66B** [comment]
Yes

**Comment by codecrak** [comment]
Ok sir

**Comment by codecrak** [comment]
[xp.txt](https://github.com/M66B/XPrivacy/files/276311/xp.txt) Sir,it just started working flawlessly . dont know how. thnx for your support brother

**Comment by Gitoffthelawn** [comment]
@codecrak I always find it interesting how digital technology can seem to break itself or fix itself.  Since it's digital, that shouldn't happen.  Obviously, something has to change, perhaps a race condition or a hardware timing issue.  Unfortunately, it's rare for people to have the time to perform a full trace to determine exactly what happened.
