### ISSUE TITLE
VPN apps don't work

### ISSUE THREAD

**Issue by dit7ya** [M66B/XPrivacy#2361]
Every VPN app shuts down immediately after opening, while XPrivacy is enabled.

**Comment by Cerberus-tm** [comment]
Have you checked the Xprivacy usage log for the VPN app?

Have you disabled all restrictions for the VPN app? Does it work then?

Are you sure it isn't another Xposed module? I remember all VPN apps refused to work for me when Onehand Mode was enabled. I think I had to whitelist some stuff in Onehand Mode in order to get VPN apps to work, because Onehand Mode would disable the pop-up screen for VPN access.

**Comment by M66B** [comment]
I don't think this is being caused by a bug in XPrivacy.
