### ISSUE TITLE
Xprivacy with the new Xposed on Android 7.1 Nougat

### ISSUE THREAD

**Issue by T-vK** [M66B/XPrivacy#2428]
Since Xposed is finally compatible with Android N, I upgraded to Lineage 14.1 and installed Xprivacy.  
So far it seems to work. No crashes so far. But there are some things that I want to mention:  
When I start Xprivacy, I get an error message "An internal check failed, do you want to send the support info?"
This message pops up twice in a row. When I tap ok and try to save it, I get this error:

```
Error saving file:
java.io.FileNotFoundException: /data/data/com.termux/files/home/downloads/XPrivacy 3.6.19/7.1.2 support info.txt (No such file or directory)
```

When I tap `Switch theme`, the same thing happens (two error messages...).

I can't provide a logcat at the moment because I can't get adb to work on my notebook. I might be able to get it from a terminal emulator, but I'm having some issues with FDroid so that has to wait.

**Comment by 8alucard8** [comment]
Nice thank you very much for your info. I may try to recreate this myself in the next days.


________________________________
Von: T-vK <notifications@github.com>
Gesendet: Montag, 30. Oktober 2017 23:39
An: M66B/XPrivacy
Cc: Subscribed
Betreff: [M66B/XPrivacy] Xprivacy with the new Xposed on Android 7.1 Nougat (#2428)


Since Xposed is finally compatible with Android N, I upgraded to Lineage 14.1 and installed Xprivacy.
So far it seems to work. No crashes so far. But there are some things that I want to mention:
When I start Xprivacy, I get an error message "An internal check failed, do you want to send the support info?"
This message pops up twice in a row. When I tap ok and try to save it, I get this error:

Error saving file:
java.io.FileNotFoundException: /data/data/com.termux/files/home/downloads/XPrivacy 3.6.19/7.1.2 support info.txt (No such file or directory)


When I tap Switch theme, the same thing happens (two error messages...).

I can't provide a logcat at the moment because I can't get adb to work on my notebook. I might be able to get it from a terminal emulator, but I'm having some issues with FDroid so that has to wait.
