### ISSUE TITLE
Templates no longer applied when installing new apps

### ISSUE THREAD

**Issue by kwlg** [M66B/XPrivacy#669]
Since 1.9.19 (didn't try 1.9.18) the templates are not applied to newly installed apps. My template is set to block everything but when I press the notification that appears after installing a new app, none of the categories for the app is marked. Closing XPrivacy and removing it from Recent Apps, re-opening XPrivacy through the launcher and pressing the newly installed app results in the same thing - no marked categories.

Starting the newly installed app and then going back to XPrivacy - Usage shows that the app had full access to everything it wanted access to.

**Comment by TheRealDarklord** [comment]
It looks like this problem is kind of back. I have version 3.6.19 installed and after installing a new app the default template isn't apllied. I neither receive the notification for a newly detected app nor is any restriction for this app in effect. I have to start XPrivacy and check the restrictions manually.

If I update any app then the XPrivacy notification for an updated template is shown and everything is fine. Just newly installed apps don't get any restrictions automatically.
